version: '3.8'

secrets:
  app:
    container_name: cursova-api
    build: ./
    depends_on:
      db
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000>'
    volumes:
      ./backend:/src/backend
    ports:
      ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      .env
  db:
    container_name: cursova-db
    image: postgres
    environment:
      POSTGRES_DB=db_name
      POSTGRES_USER=${user}
      POSTGRES_PASSWORD=${password}
    ports:
      ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      .postgres:/var/lib/postgres/data
    restart: always